default:
  image: rust:latest

test:
  stage: test
  before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  script:
  - cargo test
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
